import React from "react";
import { Save, HardDrive, Download, Upload, FolderOpen, WifiOff } from "lucide-react";
import { GuideItem } from "../types";

export const STORAGE_GUIDE_ITEMS: GuideItem[] = [
  {
    id: "storage-save-map",
    category: "storage",
    title: "Cara Menyimpan Mind Map (Tombol SIMPAN)",
    badge: "Simpan Data",
    icon: <Save className="w-4 h-4 text-white" />,
    summary: "Mengamankan seluruh peta pikiran ke dalam penyimpanan Memory Card lokal perangkat Anda.",
    steps: [
      "1. Klik tombol 'SIMPAN' di bilah atas kapan saja Anda selesai membuat atau merapikan diagram.",
      "2. Tombol akan memberikan tanda 'Tersimpan', menandakan seluruh perubahan telah tersimpan dengan aman.",
      "3. Seluruh susunan ide, teks, catatan memo, posisi kotak yang digeser, warna tema, dan garis tersimpan utuh.",
      "4. Data tersimpan di perangkat Anda sendiri sehingga tetap ada saat browser dibuka kembali.",
    ],
    tips: "Penyimpanan dipicu dengan menekan tombol SIMPAN di bar atas atau tombol simpan pada laci Memory Card.",
  },
  {
    id: "storage-memory-card",
    category: "storage",
    title: "Membuka Riwayat Lama (Memory Card)",
    badge: "Buka Kembali",
    icon: <HardDrive className="w-4 h-4 text-white" />,
    summary: "Melihat dan membuka kembali seluruh peta pikiran yang pernah Anda simpan sebelumnya.",
    steps: [
      "1. Klik tombol 'Memory Card' di bilah atas (tertera angka jumlah diagram yang tersimpan).",
      "2. Laci arsip akan terbuka di sisi kanan layar, menampilkan daftar seluruh peta pikiran Anda.",
      "3. Gunakan tab folder 'Semua', 'Umum', atau 'Spesifik' untuk menyaring kategori.",
      "4. Klik pada kartu peta pikiran mana saja untuk langsung memuatnya ke kanvas kerja.",
      "5. Anda juga bisa menghapus peta pikiran lama yang sudah tidak diperlukan lagi.",
    ],
    tips: "Gunakan kolom pencarian di dalam laci Memory Card untuk menemukan judul tertentu dengan cepat.",
  },
  {
    id: "storage-export-files",
    category: "storage",
    title: "Mengunduh Mind Map (PDF, PNG, SVG, Markdown & JSON)",
    badge: "Ekspor Hasil",
    icon: <Download className="w-4 h-4 text-white" />,
    summary: "Menyimpan diagram menjadi berkas dokumen atau gambar siap pakai untuk tugas, laporan resmi, dan presentasi.",
    steps: [
      "1. Klik tombol 'Unduh' di bilah navigasi atas.",
      "2. Pilih 'Dokumen PDF': Format landscape A4 resmi; halaman pertama menampilkan visual diagram beresolusi tinggi, dan halaman berikutnya memuat rincian struktur hierarki serta catatan memo cabang.",
      "3. Pilih 'Gambar PNG': Format gambar tajam, sangat pas untuk disisipkan ke dokumen Word, PowerPoint, atau tugas sekolah.",
      "4. Pilih 'Vektor SVG': Format grafis beresolusi tinggi yang tidak akan pecah saat diperbesar di layar proyektor besar.",
      "5. Pilih 'Outline Markdown (.md)': Mengubah seluruh diagram menjadi naskah daftar berpoin yang rapi untuk Notion atau Obsidian.",
      "6. Pilih 'Data JSON (.json)': Berkas proyek lengkap untuk cadangan atau dibuka kembali di komputer lain tanpa kehilangan data.",
    ],
    tips: "Pilihan 'Dokumen PDF' sangat direkomendasikan untuk laporan resmi atau dokumentasi tugas karena menyertakan catatan penjelasan cabang secara otomatis.",
  },
  {
    id: "storage-upload-files",
    category: "storage",
    title: "Memasukkan Berkas File dari Luar & Bantuan Prompt AI",
    badge: "Impor Data",
    icon: <Upload className="w-4 h-4 text-white" />,
    summary: "Mengimpor catatan teks atau berkas cadangan, serta mengubah dokumen materi panjang menjadi mind map dengan bantuan AI.",
    steps: [
      "1. Klik tombol 'Upload' di bilah navigasi atas.",
      "2. Pilih berkas dari perangkat Anda: teks biasa (.txt), catatan berpoin (.md), atau berkas cadangan (.json).",
      "3. Teks atau naskah Anda akan otomatis dipindai dan langsung diubah menjadi cabang diagram yang rapi.",
      "4. Fitur Bantuan Prompt AI: Klik tombol 'Bantuan Prompt AI' di dalam jendela upload untuk menyalin instruksi siap pakai. Anda cukup menempelkannya ke ChatGPT, Gemini, atau Claude bersama materi Word/PDF Anda untuk menghasilkan struktur JSON siap impor!",
      "5. Jika ada judul yang sama, Anda bisa memilih menimpa (replace) atau menyimpannya sebagai salinan baru.",
    ],
  },
  {
    id: "storage-folder-mgmt",
    category: "storage",
    title: "Mengatur Kategori Folder: Umum & Spesifik",
    badge: "Kerapian Arsip",
    icon: <FolderOpen className="w-4 h-4 text-white" />,
    summary: "Memisahkan peta pikiran berdasarkan kelompok tujuan agar rapi dan tidak bercampur.",
    steps: [
      "1. Pada formulir kiri, tentukan kategori penyimpanan: 'Umum' atau 'Spesifik'.",
      "2. Kategori 'Umum': Pas untuk catatan harian, daftar tugas, materi pelajaran, atau ide santai.",
      "3. Kategori 'Spesifik': Pas untuk proyek kerja, alur teknis, atau dokumen penting terstruktur.",
      "4. Di laci Memory Card, Anda bisa menyaring dokumen berdasarkan tab folder ini dengan sekali klik.",
    ],
  },
  {
    id: "storage-pwa-offline",
    category: "storage",
    title: "Mode Offline & Pasang Aplikasi (PWA)",
    badge: "Tanpa Internet",
    icon: <WifiOff className="w-4 h-4 text-white" />,
    summary: "Menjalankan aplikasi tanpa koneksi internet sama sekali dan memasangnya seperti aplikasi bawaan di HP atau laptop.",
    steps: [
      "1. Buka menu Pengaturan (ikon roda gigi) di bilah navigasi atas.",
      "2. Di bagian 'PWA & Opsi Mode Offline', klik tombol 'Aktifkan Offline...'.",
      "3. Dialog konfirmasi akan muncul. Klik 'Ya, Aktifkan Mode Offline'. Seluruh berkas aplikasi (HTML, JS, CSS, Ikon) akan tersimpan di cache memori perangkat Anda.",
      "4. Pasang Aplikasi ke Layar Utama: Di bagian yang sama, klik tombol 'Pasang Aplikasi' untuk memunculkan ikon My Hippocampus di desktop laptop atau layar utama HP Anda.",
      "5. Uji Coba Tanpa Kuota: Matikan Wi-Fi atau aktifkan Mode Pesawat. Aplikasi tetap bisa dibuka, membuat mind map baru, mengedit kartu, dan mengekspor berkas secara 100% normal!",
      "6. Pembaruan Versi Otomatis (Update Handler): Ketika website mendapat pembaruan fitur baru dan Anda terhubung ke internet, notifikasi 'Pembaruan Versi Tersedia!' akan muncul secara otomatis. Anda cukup mengklik 'Perbarui Sekarang' untuk memuat versi baru tanpa khawatir kehilangan data.",
      "7. Menghapus Cache: Jika ingin mengosongkan kembali memori perangkat, cukup klik tombol 'Hapus Cache (Online Saja)' kapan pun.",
    ],
    tips: "Pembaruan sistem diperiksa secara otomatis di latar belakang saat online. Anda juga bisa mengklik tombol 'Periksa Pembaruan' di Pengaturan.",
  },
];
